-- MySQL Script generated by MySQL Workbench
-- Fri Dec 10 09:01:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ModelBuilder
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ModelBuilder` ;

-- -----------------------------------------------------
-- Schema ModelBuilder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ModelBuilder` DEFAULT CHARACTER SET utf8 ;
USE `ModelBuilder` ;

-- -----------------------------------------------------
-- Table `brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brand` ;

CREATE TABLE IF NOT EXISTS `brand` (
  `brand_Id` INT NOT NULL AUTO_INCREMENT,
  `brand_Name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `brand_TimeStamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `brand_Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`brand_Id`),
  UNIQUE INDEX `brand_Name` USING BTREE (`brand_Name`) VISIBLE,
  INDEX `brand_Name` (`brand_Name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'List of brands for tools, kits, suplies and all other stuf';


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

CREATE TABLE IF NOT EXISTS `category` (
  `category_Id` INT NOT NULL AUTO_INCREMENT,
  `category_Name` VARCHAR(55) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `category_Fullpath` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `category_ParentId` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`category_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 782
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps` ;

CREATE TABLE IF NOT EXISTS `timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `contacttype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contacttype` ;

CREATE TABLE IF NOT EXISTS `contacttype` (
  `contacttype_Id` INT NOT NULL AUTO_INCREMENT,
  `contacttype_Name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  PRIMARY KEY (`contacttype_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `country` ;

CREATE TABLE IF NOT EXISTS `country` (
  `country_Id` INT NOT NULL AUTO_INCREMENT,
  `country_Code` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `country_Defaultcurrency_Symbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '€',
  `country_Name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `country_Defaultcurrency_Id` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`country_Id`),
  UNIQUE INDEX `country_Code_UNIQUE` USING BTREE (`country_Code`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `currency` ;

CREATE TABLE IF NOT EXISTS `currency` (
  `currency_Id` INT NOT NULL AUTO_INCREMENT,
  `currency_Code` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `currency_Symbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `currency_Name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `currency_ConversionRate` DOUBLE(6,4) NULL DEFAULT '1.0000',
  PRIMARY KEY USING BTREE (`currency_Id`),
  UNIQUE INDEX `currency_Code` USING BTREE (`currency_Code`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `language` ;

CREATE TABLE IF NOT EXISTS `language` (
  `language_Id` INT NOT NULL AUTO_INCREMENT,
  `language_Code` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `language_Name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`language_Id`),
  UNIQUE INDEX `language_code` USING BTREE (`language_Code`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

CREATE TABLE IF NOT EXISTS `product` (
  `product_Id` INT NOT NULL AUTO_INCREMENT,
  `product_Code` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `product_Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `product_Dimensions` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `product_Price` DOUBLE(10,2) NULL DEFAULT '0.00',
  `product_MinimalStock` DOUBLE(6,2) NULL DEFAULT '0.00',
  `product_StandardOrderQuantity` DOUBLE(6,2) NULL DEFAULT '0.00',
  `product_ProjectCosts` INT NULL DEFAULT '0',
  `product_UnitId` INT NULL DEFAULT NULL,
  `product_UnitName` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `product_ImageRotationAngle` VARCHAR(4) NULL DEFAULT '0',
  `product_Image` LONGBLOB NULL DEFAULT NULL,
  `product_BrandId` INT NULL DEFAULT NULL,
  `product_BrandName` VARCHAR(150) NULL DEFAULT NULL,
  `product_CategoryId` INT NULL DEFAULT NULL,
  `product_CategoryName` VARCHAR(55) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `product_StorageId` INT NULL DEFAULT NULL,
  `product_StorageName` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `product_Memo` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`product_Id`),
  UNIQUE INDEX `product_Code` (`product_Code` ASC) VISIBLE,
  INDEX `product_BrandName` (`product_BrandName` ASC) VISIBLE,
  CONSTRAINT `FK_product_brand`
    FOREIGN KEY (`product_BrandName`)
    REFERENCES `brand` (`brand_Name`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `productsupplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productsupplier` ;

CREATE TABLE IF NOT EXISTS `productsupplier` (
  `productSupplier_Id` INT NOT NULL AUTO_INCREMENT,
  `productSupplier_ProductId` INT NOT NULL DEFAULT '0',
  `productSupplier_SupplierId` INT NOT NULL DEFAULT '0',
  `productSupplier_SupplierName` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `productSupplier_CurrencyId` INT NOT NULL DEFAULT '0',
  `productSupplier_CurrencySymbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `productSupplier_ProductNumber` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `productSupplier_ProductName` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `productSupplier_ProductPrice` DOUBLE NOT NULL DEFAULT '0',
  `productSupplier_Default` VARCHAR(1) NULL DEFAULT '',
  PRIMARY KEY USING BTREE (`productSupplier_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'List for all products per supplier';


-- -----------------------------------------------------
-- Table `project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project` ;

CREATE TABLE IF NOT EXISTS `project` (
  `project_Id` INT NOT NULL AUTO_INCREMENT,
  `project_Code` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `project_Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `project_StartDate` DATE NULL DEFAULT NULL,
  `project_EndDate` DATE NULL DEFAULT NULL,
  `project_ExpectedTime` INT NULL DEFAULT NULL,
  `project_Image` LONGBLOB NULL DEFAULT NULL,
  `project_ImageRotationAngle` VARCHAR(4) NULL DEFAULT '0',
  `project_Closed` TINYINT NULL DEFAULT '0',
  `project_Memo` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`project_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `storage` ;

CREATE TABLE IF NOT EXISTS `storage` (
  `storage_Id` INT NOT NULL AUTO_INCREMENT,
  `storage_ParentId` INT NULL DEFAULT NULL,
  `storage_FullPath` VARCHAR(400) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `storage_Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`storage_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 265
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supplier` ;

CREATE TABLE IF NOT EXISTS `supplier` (
  `supplier_Id` INT NOT NULL AUTO_INCREMENT,
  `supplier_Code` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `supplier_Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `supplier_Address1` VARCHAR(150) NULL DEFAULT NULL,
  `supplier_Address2` VARCHAR(150) NULL DEFAULT NULL,
  `supplier_Zip` VARCHAR(15) NULL DEFAULT NULL,
  `supplier_City` VARCHAR(40) NULL DEFAULT NULL,
  `supplier_Url` VARCHAR(255) NULL DEFAULT NULL,
  `supplier_ShippingCosts` DOUBLE(6,2) NOT NULL DEFAULT '0.00',
  `supplier_OrderCosts` DOUBLE(6,2) NOT NULL DEFAULT '0.00',
  `supplier_MinShippingCosts` DOUBLE(6,2) NOT NULL DEFAULT '0.00',
  `supplier_MinOrderCosts` DOUBLE(6,2) NOT NULL DEFAULT '0.00',
  `supplier_Memo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `supplier_CurrencyId` INT NOT NULL DEFAULT '1',
  `supplier_CurrencySymbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '€',
  `supplier_CountryId` INT NOT NULL DEFAULT '1',
  `supplier_CountryName` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT 'Nederland',
  PRIMARY KEY (`supplier_Id`),
  UNIQUE INDEX `supplier_Code` (`supplier_Code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `suppliercontact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppliercontact` ;

CREATE TABLE IF NOT EXISTS `suppliercontact` (
  `suppliercontact_Id` INT NOT NULL AUTO_INCREMENT,
  `suppliercontact_SupplierId` INT NULL DEFAULT '0',
  `suppliercontact_Name` VARCHAR(150) NULL DEFAULT '',
  `suppliercontact_TypeId` INT NULL DEFAULT '1',
  `suppliercontact_TypeName` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `suppliercontact_Mail` VARCHAR(150) NULL DEFAULT '',
  `suppliercontact_Phone` VARCHAR(150) NULL DEFAULT '',
  PRIMARY KEY (`suppliercontact_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supplyorder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supplyorder` ;

CREATE TABLE IF NOT EXISTS `supplyorder` (
  `order_Id` INT NOT NULL AUTO_INCREMENT,
  `order_SupplierId` INT NULL DEFAULT '0',
  `order_CurrencyId` INT NULL DEFAULT '0',
  `order_OrderNumber` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `order_SupplierName` VARCHAR(150) NULL DEFAULT NULL,
  `order_Date` DATE NULL DEFAULT NULL,
  `order_CurrencySymbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '€',
  `order_CurrencyConversionRate` DOUBLE(6,4) NULL DEFAULT '0.0000',
  `order_ShippingCosts` DOUBLE(10,2) NULL DEFAULT '0.00',
  `order_OrderCosts` DOUBLE(10,2) NULL DEFAULT '0.00',
  `order_Memo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `order_Closed` TINYINT NULL DEFAULT '0',
  `order_ClosedDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`order_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `supplyorderline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supplyorderline` ;

CREATE TABLE IF NOT EXISTS `supplyorderline` (
  `orderline_Id` INT NOT NULL AUTO_INCREMENT,
  `orderline_OrderId` INT NOT NULL DEFAULT '0',
  `orderline_SupplierId` INT NOT NULL DEFAULT '0',
  `orderline_ProductId` INT NULL DEFAULT '0',
  `orderline_ProductName` VARCHAR(150) NULL DEFAULT '',
  `orderline_ProjectId` INT NULL DEFAULT '0',
  `orderline_ProjectName` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `orderline_CategoryId` INT NULL DEFAULT '0',
  `orderline_CategoryName` VARCHAR(55) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `orderline_Number` DOUBLE(6,2) NULL DEFAULT '0.00',
  `orderline_Price` DOUBLE(6,2) NULL DEFAULT '0.00',
  `orderline_RealRowTotal` DOUBLE(6,2) NULL DEFAULT '0.00',
  `orderline_Closed` TINYINT NULL DEFAULT '0',
  `orderline_ClosedDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`orderline_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unit` ;

CREATE TABLE IF NOT EXISTS `unit` (
  `unit_Id` INT NOT NULL AUTO_INCREMENT,
  `unit_Name` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '0',
  PRIMARY KEY (`unit_Id`),
  UNIQUE INDEX `unit_Name` (`unit_Name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `worktype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worktype` ;

CREATE TABLE IF NOT EXISTS `worktype` (
  `worktype_Id` INT NOT NULL AUTO_INCREMENT,
  `worktype_ParentId` INT NULL DEFAULT NULL,
  `worktype_Name` CHAR(150) NULL DEFAULT NULL,
  `worktype_FullPath` CHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`worktype_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
