-- MySQL Script generated by MySQL Workbench
-- Mon Dec 13 10:52:53 2021
-- Model: Modelbuilder    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ModelBuilder
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ModelBuilder` ;

-- -----------------------------------------------------
-- Schema ModelBuilder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ModelBuilder` DEFAULT CHARACTER SET utf8 ;
USE `ModelBuilder` ;

-- -----------------------------------------------------
-- Table `brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brand` ;

CREATE TABLE IF NOT EXISTS `brand` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name` USING BTREE (`Name`) VISIBLE,
  INDEX `Name` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'List of brands for tools, kits, suplies and all other stuf';


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

CREATE TABLE IF NOT EXISTS `category` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ParentId` INT NULL DEFAULT NULL,
  `Name` VARCHAR(55) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Fullpath` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY USING BTREE (`Id`),
  INDEX `Name` (`Name` ASC) INVISIBLE,
  INDEX `FullPath` (`Fullpath` ASC) INVISIBLE,
  INDEX `ParentId` (`ParentId` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 782
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `contacttype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contacttype` ;

CREATE TABLE IF NOT EXISTS `contacttype` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  INDEX `Name` (`Name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `country` ;

CREATE TABLE IF NOT EXISTS `country` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `DefaultSymbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '€',
  `Name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `DefaultId` INT NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY USING BTREE (`Id`),
  UNIQUE INDEX `Code_UNIQUE` USING BTREE (`Code`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `currency` ;

CREATE TABLE IF NOT EXISTS `currency` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `Symbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `Name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ConversionRate` DOUBLE(6,4) NULL DEFAULT '1.0000',
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY USING BTREE (`Id`),
  UNIQUE INDEX `Code` USING BTREE (`Code`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `language` ;

CREATE TABLE IF NOT EXISTS `language` (
  `language_Id` INT NOT NULL AUTO_INCREMENT,
  `language_Code` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `language_Name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`language_Id`),
  UNIQUE INDEX `language_code` USING BTREE (`language_Code`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

CREATE TABLE IF NOT EXISTS `product` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Dimensions` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `Price` DOUBLE(10,2) NULL DEFAULT '0.00',
  `MinimalStock` DOUBLE(6,2) NULL DEFAULT '0.00',
  `StandardOrderQuantity` DOUBLE(6,2) NULL DEFAULT '0.00',
  `ProjectCosts` INT NULL DEFAULT '0',
  `Id` INT NULL DEFAULT NULL,
  `ImageRotationAngle` VARCHAR(4) NULL DEFAULT '0',
  `Image` LONGBLOB NULL DEFAULT NULL,
  `Id` INT NULL DEFAULT NULL,
  `Id` INT NULL DEFAULT NULL,
  `Id` INT NULL DEFAULT NULL,
  `Memo` LONGTEXT NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Code` (`Code` ASC) INVISIBLE,
  INDEX `Id` (`Id` ASC) VISIBLE,
  INDEX `Id` (`Id` ASC) INVISIBLE,
  INDEX `Id` (`Id` ASC) INVISIBLE,
  INDEX `Id` (`Id` ASC) VISIBLE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `brand` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `category` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `unit` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `storage` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `productsupplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productsupplier` ;

CREATE TABLE IF NOT EXISTS `productsupplier` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Id` INT NOT NULL DEFAULT '0',
  `Id` INT NOT NULL DEFAULT '0',
  `Id` INT NOT NULL DEFAULT '0',
  `ProductNumber` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Price` DOUBLE NOT NULL DEFAULT '0',
  `Default` VARCHAR(1) NULL DEFAULT '',
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY USING BTREE (`Id`),
  INDEX `Id` (`Id` ASC) INVISIBLE,
  INDEX `Id` (`Id` ASC) VISIBLE,
  INDEX `Id` (`Id` ASC) VISIBLE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `product` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `supplier` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `currency` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'List for all products per supplier';


-- -----------------------------------------------------
-- Table `project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project` ;

CREATE TABLE IF NOT EXISTS `project` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `StartDate` DATE NULL DEFAULT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `ExpectedTime` INT NULL DEFAULT NULL,
  `Image` LONGBLOB NULL DEFAULT NULL,
  `ImageRotationAngle` VARCHAR(4) NULL DEFAULT '0',
  `Memo` LONGTEXT NULL DEFAULT NULL,
  `Closed` TINYINT NULL DEFAULT '0',
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY USING BTREE (`Id`),
  UNIQUE INDEX `Code` (`Code` ASC) INVISIBLE,
  INDEX `Name` (`Name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `storage` ;

CREATE TABLE IF NOT EXISTS `storage` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ParentId` INT NULL DEFAULT NULL,
  `FullPath` VARCHAR(400) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 265
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supplier` ;

CREATE TABLE IF NOT EXISTS `supplier` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Address1` VARCHAR(150) NULL DEFAULT NULL,
  `Address2` VARCHAR(150) NULL DEFAULT NULL,
  `Zip` VARCHAR(15) NULL DEFAULT NULL,
  `City` VARCHAR(40) NULL DEFAULT NULL,
  `Url` VARCHAR(255) NULL DEFAULT NULL,
  `ShippingCosts` DOUBLE(6,2) NOT NULL DEFAULT '0.00',
  `MinShippingCosts` DOUBLE(6,2) NOT NULL DEFAULT '0.00',
  `OrderCosts` DOUBLE(6,2) NOT NULL DEFAULT '0.00',
  `Memo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Id` INT NOT NULL DEFAULT '1',
  `Id` INT NOT NULL DEFAULT '1',
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Code` (`Code` ASC) INVISIBLE,
  INDEX `Name` (`Name` ASC) INVISIBLE,
  INDEX `Id` (`Id` ASC) INVISIBLE,
  INDEX `Id` (`Id` ASC) VISIBLE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `currency` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `country` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `suppliercontact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppliercontact` ;

CREATE TABLE IF NOT EXISTS `suppliercontact` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Id` INT NULL DEFAULT '0',
  `Name` VARCHAR(150) NULL DEFAULT '',
  `Id` INT NULL DEFAULT '1',
  `Mail` VARCHAR(150) NULL DEFAULT '',
  `Phone` VARCHAR(150) NULL DEFAULT '',
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  INDEX `Id` (`Id` ASC) VISIBLE,
  INDEX `Id` (`Id` ASC) INVISIBLE,
  INDEX `Name` (`Name` ASC) VISIBLE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `supplier` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `contacttype` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supplyorder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supplyorder` ;

CREATE TABLE IF NOT EXISTS `supplyorder` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Id` INT NULL DEFAULT '0',
  `Id` INT NULL DEFAULT '0',
  `OrderNumber` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `OrderDate` DATE NULL DEFAULT NULL,
  `CurrencySymbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '€',
  `CurrencyConversionRate` DOUBLE(6,4) NULL DEFAULT '0.0000',
  `ShippingCosts` DOUBLE(10,2) NULL DEFAULT '0.00',
  `OrderCosts` DOUBLE(10,2) NULL DEFAULT '0.00',
  `Memo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Closed` TINYINT NULL DEFAULT '0',
  `ClosedDate` DATE NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY USING BTREE (`Id`),
  INDEX `OrderNumber` () VISIBLE,
  INDEX `FK_Id_idx` (`Id` ASC) VISIBLE,
  INDEX `FK_Id_idx` (`Id` ASC) VISIBLE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `supplier` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `currency` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `supplyorderline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supplyorderline` ;

CREATE TABLE IF NOT EXISTS `supplyorderline` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Id` INT NOT NULL DEFAULT '0',
  `Id` INT NOT NULL DEFAULT '0',
  `Id` INT NULL DEFAULT '0',
  `SupplierProductName` VARCHAR(150) NULL DEFAULT '',
  `Id` INT NULL DEFAULT '0',
  `Id` INT NULL DEFAULT '0',
  `Amount` DOUBLE(6,2) NULL DEFAULT '0.00',
  `Price` DOUBLE(6,2) NULL DEFAULT '0.00',
  `RealRowTotal` DOUBLE(6,2) NULL DEFAULT '0.00',
  `Closed` TINYINT NULL DEFAULT '0',
  `ClosedDate` DATE NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY USING BTREE (`Id`),
  INDEX `FK_Suupplyorder_Id_idx` (`Id` ASC) VISIBLE,
  INDEX `FK_Id_idx` (`Id` ASC) VISIBLE,
  INDEX `FK_Id_idx` (`Id` ASC) VISIBLE,
  INDEX `FK_idx` (`Id` ASC, `Id` ASC) VISIBLE,
  INDEX `FK_Id_idx` (`Id` ASC) VISIBLE,
  INDEX `FK_Id_idx` (`Id` ASC) VISIBLE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `supplyorder` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `supplier` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `product` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ProductSupplier`
    FOREIGN KEY (`Id` , `Id`)
    REFERENCES `productsupplier` (`Id` , `Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `project` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Id`
    FOREIGN KEY (`Id`)
    REFERENCES `category` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps` ;

CREATE TABLE IF NOT EXISTS `timestamps` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(150) NULL DEFAULT '',
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `Name` () VISIBLE);


-- -----------------------------------------------------
-- Table `timestamps_1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps_1` ;

CREATE TABLE IF NOT EXISTS `timestamps_1` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unit` ;

CREATE TABLE IF NOT EXISTS `unit` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '0',
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modifief` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name` (`Name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `worktype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worktype` ;

CREATE TABLE IF NOT EXISTS `worktype` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ParentId` INT NULL DEFAULT NULL,
  `Name` CHAR(150) NULL DEFAULT NULL,
  `FullPath` CHAR(255) NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `brand`
-- -----------------------------------------------------
START TRANSACTION;
USE `ModelBuilder`;
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (51, 'Proxxon', '2004-03-10 08:50:37', '2004-03-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (2, 'Dremel', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (3, 'Excel', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (4, 'Amati', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (5, 'Artesania Latina', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (6, 'Mantua', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (7, 'Modelcraft', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (8, 'Occre', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (9, 'Revell', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (10, 'Humbrol', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (11, 'Tamiya', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (12, 'Billing Boats', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (13, 'Model Shipways', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (14, 'Caldercraft', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (15, 'Constructo', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (16, 'Krick', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (17, 'Aeronaut', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (18, 'Corel', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (19, 'Panart', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (20, 'Sergal', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (21, 'CAP', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (22, 'CMK Czech', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (23, 'Disar', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (24, 'Dumas', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (25, 'Graupner', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (26, 'Mamoli', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (27, 'Shipyard', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (28, 'UHU', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (29, 'ZAP', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (30, 'Super Glue', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (31, 'Admirality', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (32, 'Aliphatic', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (33, 'Ever Build', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (34, 'Badger', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (35, 'Rotacraft', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (36, 'David', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (37, 'HobbyZone', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (38, 'Vallejo', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (39, 'AMMO Mig', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (40, 'Master Tools,2021-12-10 08:50:37\"', '2021-12-10 08:50:37', '');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (41, 'Trumpeter', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (42, 'Faller', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (43, 'HMB', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (44, 'Proedge', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (45, 'Kinzo', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (46, 'Praxis', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (47, 'Gamma', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (48, 'Bosch', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (49, 'Makita', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (50, 'Xuron', '2021-12-10 08:50:37', '2021-12-10 08:50:37');
INSERT INTO `brand` (`Id`, `Name`, `Modified`, `Created`) VALUES (1, '_Geen_', '2021-12-10 08:50:37', '2021-12-10 08:50:37');

COMMIT;


-- -----------------------------------------------------
-- Data for table `category`
-- -----------------------------------------------------
START TRANSACTION;
USE `ModelBuilder`;
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (1, NULL, 'Afwerking', 'Afwerking', '2021-12-10 12:39:38', '2020-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (2, 1, 'Veroudering/Bruinering', 'Afwerking\\Veroudering/Bruinering', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (3, 1, 'Maskering', 'Afwerking\\Maskering', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (4, 1, 'Penselen', 'Afwerking\\Penselen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (5, 1, 'Verf', 'Afwerking\\Verf', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (6, 1, 'Lak', 'Afwerking\\Lak', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (7, 1, 'Lijm', 'Afwerking\\Lijm', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (8, 7, 'Houtlijm', 'Afwerking\\Lijm\\Houtlijm', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (9, 7, 'Secondenlijm', 'Afwerking\\Lijm\\Secondenlijm', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (10, NULL, 'Gereedschapeedschap', 'Gereedschap', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (11, 10, 'Algemeen', 'Gereedschap\\Algemeen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (12, 11, 'Accessoires', 'Gereedschap\\Algemeen\\Accessoires', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (13, 10, 'Elektrisch', 'Gereedschap\\Elektrisch', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (14, 13, 'Accessoires', 'Gereedschap\\Elektrisch\\Accessoires', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (15, 10, 'Hand', 'Gereedschap\\Hand', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (16, 15, 'Accessoires', 'Gereedschap\\Hand\\Accessoires', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (17, 10, 'Meetgereedschap', 'Gereedschap\\Meetgereedschap', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (18, 17, 'Accessoires', 'Gereedschap\\Meetgereedschap\\Accessoires', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (19, NULL, 'Hulpmiddelen', 'Hulpmiddelen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (20, 19, 'Opbergmiddelen', 'Hulpmiddelen\\Opbergmiddelen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (21, 19, 'Schuurpapier', 'Hulpmiddelen\\Schuurpapier', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (22, NULL, 'Materiaal', 'Materiaal', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (23, 22, 'Scheepsbeslag', 'Materiaal\\Scheepsbeslag', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (24, 23, 'Ankers', 'Materiaal\\Scheepsbeslag\\Ankers', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (25, 23, 'Boegbeelden', 'Materiaal\\Scheepsbeslag\\Boegbeelden', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (26, 23, 'Scheepsbellen/hoorns', 'Materiaal\\Scheepsbeslag\\Scheepsbellen/hoorns', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (27, 23, 'Blokken', 'Materiaal\\Scheepsbeslag\\Blokken', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (28, 23, 'Kikkers/Bolders/Klampen', 'Materiaal\\Scheepsbeslag\\Kikkers/Bolders/Klampen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (29, 23, 'Bijboten', 'Materiaal\\Scheepsbeslag\\Bijboten', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (30, 23, 'Dekattributen', 'Materiaal\\Scheepsbeslag\\Dekattributen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (31, 23, 'Scheepsklokken', 'Materiaal\\Scheepsbeslag\\Scheepsklokken', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (32, 23, 'Lantaarns', 'Materiaal\\Scheepsbeslag\\Lantaarns', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (33, 23, 'Mastvoetten', 'Materiaal\\Scheepsbeslag\\Mastvoeten', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (34, 23, 'Korvijnagels(Belayingpins)', 'Materiaal\\Scheepsbeslag\\Korvijnagels(Belayingpins)', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (35, 23, 'Ogen', 'Materiaal\\Scheepsbeslag\\Ogen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (36, 23, 'Bevestigingspinnen', 'Materiaal\\Scheepsbeslag\\Bevestigingspinnen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (37, 23, 'Pompen', 'Materiaal\\Scheepsbeslag\\Pompen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (38, 23, 'Patrijspoorten', 'Materiaal\\Scheepsbeslag\\Patrijspoorten', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (39, 23, 'Roosters', 'Materiaal\\Scheepsbeslag\\Roosters', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (40, 23, 'Geschut', 'Materiaal\\Scheepsbeslag\\Geschut', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (41, 23, 'Stuurwielen', 'Materiaal\\Scheepsbeslag\\Stuurwielen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (42, 23, 'Trappen', 'Materiaal\\Scheepsbeslag\\Trappen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (43, 23, 'Vlaggenmasten', 'Materiaal\\Scheepsbeslag\\Vlaggenmasten', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (44, 23, 'Want/Mast/Geleiding', 'Materiaal\\Scheepsbeslag\\Want/Mast/Geleiding', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (45, 22, 'Beuken', 'Materiaal\\Beuken', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (46, 45, 'Lat', 'Materiaal\\Beuken\\Lat', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (47, 45, 'Plaat', 'Materiaal\\Beuken\\Plaat', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (48, 45, 'Profiel', 'Materiaal\\Beuken\\Profiel', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (49, 45, 'Rond', 'Materiaal\\Beuken\\Rond', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (50, 45, 'Vierkant', 'Materiaal\\Beuken\\Vierkant', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (51, 22, 'Eiken', 'Materiaal\\Eiken', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (52, 51, 'Lat', 'Materiaal\\Eiken\\Lat', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (53, 51, 'Plaat', 'Materiaal\\Eiken\\Plaat', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (54, 51, 'Profiel', 'Materiaal\\Eiken\\Profiel', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (55, 51, 'Rond', 'Materiaal\\Eiken\\Rond', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (56, 51, 'Vierkant', 'Materiaal\\Eiken\\Vierkant', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (57, 22, 'Garen', 'Materiaal\\Garen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (58, 57, 'Beige', 'Materiaal\\Garen\\Beige', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (59, 57, 'Bruin', 'Materiaal\\Garen\\Bruin', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (60, 57, 'Wit', 'Materiaal\\Garen\\Wit', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (61, 57, 'Zwart', 'Materiaal\\Garen\\Zwart', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (62, 22, 'Koper', 'Materiaal\\Koper', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (63, 62, 'Draad', 'Materiaal\\Koper\\Draad', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (64, 62, 'Plaat', 'Materiaal\\Koper\\Plaat', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (65, 62, 'Profiel', 'Materiaal\\Koper\\Profiel', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (66, 62, 'Rond', 'Materiaal\\Koper\\Rond', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (67, 62, 'Strip', 'Materiaal\\Koper\\Strip', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (68, 62, 'Vierkant', 'Materiaal\\Koper\\Vierkant', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (69, 22, 'Kunststof', 'Materiaal\\Kunststof', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (70, 69, 'Plaat', 'Materiaal\\Kunststof\\Plaat', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (71, 69, 'Profiel', 'Materiaal\\Kunststof\\Profiel', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (72, 69, 'Rond', 'Materiaal\\Kunststof\\Rond', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (73, 69, 'Strip', 'Materiaal\\Kunststof\\Strip', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (74, 69, 'Vierkant', 'Materiaal\\Kunststof\\Vierkant', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (75, 22, 'Mahoni', 'Materiaal\\Mahoni', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (76, 75, 'Lat', 'Materiaal\\Mahoni\\Lat', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (77, 75, 'Plaat', 'Materiaal\\Mahoni\\Plaat', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (78, 75, 'Profiel', 'Materiaal\\Mahoni\\Profiel', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (79, 75, 'Rond', 'Materiaal\\Mahoni\\Rond', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (80, 75, 'Vierkant', 'Materiaal\\Mahoni\\Vierkant', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (81, 22, 'Messing', 'Materiaal\\Messing', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (82, 81, 'Draad', 'Materiaal\\Messing\\Draad', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (83, 81, 'Plaat', 'Materiaal\\Messing\\Plaat', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (84, 81, 'Profiel', 'Materiaal\\Messing\\Profiel', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (85, 81, 'Rond', 'Materiaal\\Messing\\Rond', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (86, 81, 'Strip', 'Materiaal\\Messing\\Strip', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (87, 81, 'Vierkant', 'Materiaal\\Messing\\Vierkant', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (88, 22, 'Noten', 'MateriaalNULLoten', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (89, 88, 'Lat', 'MateriaalNULLoten\\Lat', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (90, 88, 'Plaat', 'MateriaalNULLoten\\Plaat', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (91, 88, 'Profiel', 'MateriaalNULLoten\\Profiel', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (92, 88, 'Rond', 'MateriaalNULLoten\\Rond', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (93, 88, 'Vierkant', 'MateriaalNULLoten\\Vierkant', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (94, 22, 'Vuren', 'Materiaal\\Vuren', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (100, 22, 'Zeilen', 'Materiaal\\Zeilen', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (101, 100, 'Bruin', 'Materiaal\\Zeilen\\Bruin', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (102, 100, 'Creme', 'Materiaal\\Zeilen\\Creme', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (103, 100, 'Wit', 'Materiaal\\Zeilen\\Wit', '2021-12-10 12:39:38', '2021-12-10 12:40:29');
INSERT INTO `category` (`Id`, `ParentId`, `Name`, `Fullpath`, `Created`, `Modified`) VALUES (104, 100, 'Zwart', 'Materiaal\\Zeilen\\Zwart', '2021-12-10 12:39:38', '2021-12-10 12:40:29');

COMMIT;


-- -----------------------------------------------------
-- Data for table `contacttype`
-- -----------------------------------------------------
START TRANSACTION;
USE `ModelBuilder`;
INSERT INTO `contacttype` (`Id`, `Name`, `Created`, `Modified`) VALUES (1, NULL, '2021-12-10 12:39:38', '2021-12-10 12:39:38');
INSERT INTO `contacttype` (`Id`, `Name`, `Created`, `Modified`) VALUES (2, 'Verkoop', '2021-12-10 12:39:38', '2021-12-10 12:39:38');
INSERT INTO `contacttype` (`Id`, `Name`, `Created`, `Modified`) VALUES (3, 'Administratie', '2021-12-10 12:39:38', '2021-12-10 12:39:38');
INSERT INTO `contacttype` (`Id`, `Name`, `Created`, `Modified`) VALUES (4, 'Algemeen', '2021-12-10 12:39:38', '2021-12-10 12:39:38');

COMMIT;

