-- MySQL Script generated by MySQL Workbench
-- Fri Dec 10 09:01:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ModelBuilder
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ModelBuilder` ;

-- -----------------------------------------------------
-- Schema ModelBuilder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ModelBuilder` DEFAULT CHARACTER SET utf8 ;
USE `ModelBuilder` ;

-- -----------------------------------------------------
-- Table `brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brand` ;

CREATE TABLE IF NOT EXISTS `brand` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `TimeStamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name` USING BTREE (`Name`) VISIBLE,
  INDEX `Name` (`Name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'List of brands for tools, kits, suplies and all other stuf';


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

CREATE TABLE IF NOT EXISTS `category` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(55) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Fullpath` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ParentId` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 782
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps` ;

CREATE TABLE IF NOT EXISTS `timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `contacttype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contacttype` ;

CREATE TABLE IF NOT EXISTS `contacttype` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `country` ;

CREATE TABLE IF NOT EXISTS `country` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `DefaultSymbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '€',
  `Name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `DefaultId` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`Id`),
  UNIQUE INDEX `Code_UNIQUE` USING BTREE (`Code`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `currency` ;

CREATE TABLE IF NOT EXISTS `currency` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `Symbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `Name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ConversionRate` DOUBLE(6,4) NULL DEFAULT '1.0000',
  PRIMARY KEY USING BTREE (`Id`),
  UNIQUE INDEX `Code` USING BTREE (`Code`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `language` ;

CREATE TABLE IF NOT EXISTS `language` (
  `language_Id` INT NOT NULL AUTO_INCREMENT,
  `language_Code` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `language_Name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`language_Id`),
  UNIQUE INDEX `language_code` USING BTREE (`language_Code`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

CREATE TABLE IF NOT EXISTS `product` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Dimensions` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `Price` DOUBLE(10,2) NULL DEFAULT '0.00',
  `MinimalStock` DOUBLE(6,2) NULL DEFAULT '0.00',
  `StandardOrderQuantity` DOUBLE(6,2) NULL DEFAULT '0.00',
  `ProjectCosts` INT NULL DEFAULT '0',
  `UnitId` INT NULL DEFAULT NULL,
  `UnitName` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ImageRotationAngle` VARCHAR(4) NULL DEFAULT '0',
  `Image` LONGBLOB NULL DEFAULT NULL,
  `BrandId` INT NULL DEFAULT NULL,
  `BrandName` VARCHAR(150) NULL DEFAULT NULL,
  `CategoryId` INT NULL DEFAULT NULL,
  `CategoryName` VARCHAR(55) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `StorageId` INT NULL DEFAULT NULL,
  `StorageName` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Memo` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Code` (`Code` ASC) VISIBLE,
  INDEX `BrandName` (`BrandName` ASC) VISIBLE,
  CONSTRAINT `FK_brand`
    FOREIGN KEY (`BrandName`)
    REFERENCES `brand` (`Name`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `productsupplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productsupplier` ;

CREATE TABLE IF NOT EXISTS `productsupplier` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ProductId` INT NOT NULL DEFAULT '0',
  `SupplierId` INT NOT NULL DEFAULT '0',
  `SupplierName` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CurrencyId` INT NOT NULL DEFAULT '0',
  `CurrencySymbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `ProductNumber` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ProductName` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ProductPrice` DOUBLE NOT NULL DEFAULT '0',
  `Default` VARCHAR(1) NULL DEFAULT '',
  PRIMARY KEY USING BTREE (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'List for all products per supplier';


-- -----------------------------------------------------
-- Table `project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project` ;

CREATE TABLE IF NOT EXISTS `project` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '',
  `Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `StartDate` DATE NULL DEFAULT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `ExpectedTime` INT NULL DEFAULT NULL,
  `Image` LONGBLOB NULL DEFAULT NULL,
  `ImageRotationAngle` VARCHAR(4) NULL DEFAULT '0',
  `Closed` TINYINT NULL DEFAULT '0',
  `Memo` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `storage` ;

CREATE TABLE IF NOT EXISTS `storage` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ParentId` INT NULL DEFAULT NULL,
  `FullPath` VARCHAR(400) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 265
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supplier` ;

CREATE TABLE IF NOT EXISTS `supplier` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Address1` VARCHAR(150) NULL DEFAULT NULL,
  `Address2` VARCHAR(150) NULL DEFAULT NULL,
  `Zip` VARCHAR(15) NULL DEFAULT NULL,
  `City` VARCHAR(40) NULL DEFAULT NULL,
  `Url` VARCHAR(255) NULL DEFAULT NULL,
  `ShippingCosts` DOUBLE(6,2) NOT NULL DEFAULT '0.00',
  `OrderCosts` DOUBLE(6,2) NOT NULL DEFAULT '0.00',
  `MinShippingCosts` DOUBLE(6,2) NOT NULL DEFAULT '0.00',
  `MinOrderCosts` DOUBLE(6,2) NOT NULL DEFAULT '0.00',
  `Memo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CurrencyId` INT NOT NULL DEFAULT '1',
  `CurrencySymbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '€',
  `CountryId` INT NOT NULL DEFAULT '1',
  `CountryName` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT 'Nederland',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Code` (`Code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `suppliercontact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suppliercontact` ;

CREATE TABLE IF NOT EXISTS `suppliercontact` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `SupplierId` INT NULL DEFAULT '0',
  `Name` VARCHAR(150) NULL DEFAULT '',
  `TypeId` INT NULL DEFAULT '1',
  `TypeName` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `Mail` VARCHAR(150) NULL DEFAULT '',
  `Phone` VARCHAR(150) NULL DEFAULT '',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `supplyorder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supplyorder` ;

CREATE TABLE IF NOT EXISTS `supplyorder` (
  `order_Id` INT NOT NULL AUTO_INCREMENT,
  `order_SupplierId` INT NULL DEFAULT '0',
  `order_CurrencyId` INT NULL DEFAULT '0',
  `order_OrderNumber` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `order_SupplierName` VARCHAR(150) NULL DEFAULT NULL,
  `order_Date` DATE NULL DEFAULT NULL,
  `order_CurrencySymbol` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '€',
  `order_CurrencyConversionRate` DOUBLE(6,4) NULL DEFAULT '0.0000',
  `order_ShippingCosts` DOUBLE(10,2) NULL DEFAULT '0.00',
  `order_OrderCosts` DOUBLE(10,2) NULL DEFAULT '0.00',
  `order_Memo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `order_Closed` TINYINT NULL DEFAULT '0',
  `order_ClosedDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`order_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `supplyorderline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supplyorderline` ;

CREATE TABLE IF NOT EXISTS `supplyorderline` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `OrderId` INT NOT NULL DEFAULT '0',
  `SupplierId` INT NOT NULL DEFAULT '0',
  `ProductId` INT NULL DEFAULT '0',
  `ProductName` VARCHAR(150) NULL DEFAULT '',
  `ProjectId` INT NULL DEFAULT '0',
  `ProjectName` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `CategoryId` INT NULL DEFAULT '0',
  `CategoryName` VARCHAR(55) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '',
  `Number` DOUBLE(6,2) NULL DEFAULT '0.00',
  `Price` DOUBLE(6,2) NULL DEFAULT '0.00',
  `RealRowTotal` DOUBLE(6,2) NULL DEFAULT '0.00',
  `Closed` TINYINT NULL DEFAULT '0',
  `ClosedDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unit` ;

CREATE TABLE IF NOT EXISTS `unit` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name` (`Name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `worktype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worktype` ;

CREATE TABLE IF NOT EXISTS `worktype` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ParentId` INT NULL DEFAULT NULL,
  `Name` CHAR(150) NULL DEFAULT NULL,
  `FullPath` CHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
