//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelbuilder.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cultures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cultures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modelbuilder.Languages.Cultures", typeof(Cultures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoriën.
        /// </summary>
        public static string metadataCategory_Page_Title {
            get {
                return ResourceManager.GetString("metadataCategory.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landen.
        /// </summary>
        public static string metadataCountry_Page_Title {
            get {
                return ResourceManager.GetString("metadataCountry.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta.
        /// </summary>
        public static string metadataCurrency_Field_Currency {
            get {
                return ResourceManager.GetString("metadataCurrency.Field.Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta code.
        /// </summary>
        public static string metadataCurrency_Field_CurrencyCode {
            get {
                return ResourceManager.GetString("metadataCurrency.Field.CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta omschrijving.
        /// </summary>
        public static string metadataCurrency_Field_CurrencyName {
            get {
                return ResourceManager.GetString("metadataCurrency.Field.CurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omrekenkoers.
        /// </summary>
        public static string metadataCurrency_Field_CurrencyRate {
            get {
                return ResourceManager.GetString("metadataCurrency.Field.CurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koers.
        /// </summary>
        public static string metadataCurrency_Field_CurrencyRateShort {
            get {
                return ResourceManager.GetString("metadataCurrency.Field.CurrencyRateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta symbool.
        /// </summary>
        public static string metadataCurrency_Field_CurrencySymbol {
            get {
                return ResourceManager.GetString("metadataCurrency.Field.CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta.
        /// </summary>
        public static string metadataCurrency_Page_Title {
            get {
                return ResourceManager.GetString("metadataCurrency.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta toevoegen.
        /// </summary>
        public static string metadataCurrency_Toolbar_Button_Tooltip_Add {
            get {
                return ResourceManager.GetString("metadataCurrency.Toolbar.Button.Tooltip.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geslecteerde valuta verwijderen.
        /// </summary>
        public static string metadataCurrency_Toolbar_Button_Tooltip_Delete {
            get {
                return ResourceManager.GetString("metadataCurrency.Toolbar.Button.Tooltip.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzigingen opslaan.
        /// </summary>
        public static string metadataCurrency_Toolbar_Button_Tooltip_Save {
            get {
                return ResourceManager.GetString("metadataCurrency.Toolbar.Button.Tooltip.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producten.
        /// </summary>
        public static string metadataProduct_Page_Title {
            get {
                return ResourceManager.GetString("metadataProduct.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projecten.
        /// </summary>
        public static string metadataProject_Page_Title {
            get {
                return ResourceManager.GetString("metadataProject.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectgegevens.
        /// </summary>
        public static string metadataProject_TabItemHeader_General {
            get {
                return ResourceManager.GetString("metadataProject.TabItemHeader.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvullende informatie.
        /// </summary>
        public static string metadataProject_TabItemHeader_Memo {
            get {
                return ResourceManager.GetString("metadataProject.TabItemHeader.Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosten.
        /// </summary>
        public static string metadataProject_TabItemHeader_ProjectCosts {
            get {
                return ResourceManager.GetString("metadataProject.TabItemHeader.ProjectCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouwtijden.
        /// </summary>
        public static string metadataProject_TabItemHeader_TimeManagement {
            get {
                return ResourceManager.GetString("metadataProject.TabItemHeader.TimeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaglocaties.
        /// </summary>
        public static string metadataStorage_Page_Title {
            get {
                return ResourceManager.GetString("metadataStorage.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveranciers.
        /// </summary>
        public static string metadataSupplier_Page_Title {
            get {
                return ResourceManager.GetString("metadataSupplier.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werksoorten.
        /// </summary>
        public static string metadataWorktype_Page_Title {
            get {
                return ResourceManager.GetString("metadataWorktype.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Order_Datagrid_Header_Id {
            get {
                return ResourceManager.GetString("Order.Datagrid.Header.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geleverd.
        /// </summary>
        public static string Order_Datagrid_Header_OrderCompleted {
            get {
                return ResourceManager.GetString("Order.Datagrid.Header.OrderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besteldatum.
        /// </summary>
        public static string Order_Datagrid_Header_OrderDate {
            get {
                return ResourceManager.GetString("Order.Datagrid.Header.OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierID.
        /// </summary>
        public static string Order_Datagrid_Header_SupplierId {
            get {
                return ResourceManager.GetString("Order.Datagrid.Header.SupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverancier.
        /// </summary>
        public static string Order_Datagrid_Header_SupplierName {
            get {
                return ResourceManager.GetString("Order.Datagrid.Header.SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geleverd.
        /// </summary>
        public static string Order_Order_Field_Closed {
            get {
                return ResourceManager.GetString("Order.Order.Field.Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverdatum.
        /// </summary>
        public static string Order_Order_Field_ClosedDate {
            get {
                return ResourceManager.GetString("Order.Order.Field.ClosedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisselkoers.
        /// </summary>
        public static string Order_Order_Field_CurrencyRate {
            get {
                return ResourceManager.GetString("Order.Order.Field.CurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta.
        /// </summary>
        public static string Order_Order_Field_CurrencySymbol {
            get {
                return ResourceManager.GetString("Order.Order.Field.CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order kosten.
        /// </summary>
        public static string Order_Order_Field_OrderCosts {
            get {
                return ResourceManager.GetString("Order.Order.Field.OrderCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order datum.
        /// </summary>
        public static string Order_Order_Field_OrderDate {
            get {
                return ResourceManager.GetString("Order.Order.Field.OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordernummer.
        /// </summary>
        public static string Order_Order_Field_OrderNumber {
            get {
                return ResourceManager.GetString("Order.Order.Field.OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzendkosten.
        /// </summary>
        public static string Order_Order_Field_ShippingCosts {
            get {
                return ResourceManager.GetString("Order.Order.Field.ShippingCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverancier.
        /// </summary>
        public static string Order_Order_Field_Supplier {
            get {
                return ResourceManager.GetString("Order.Order.Field.Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelgegevens.
        /// </summary>
        public static string Order_Order_Group_Orderinformation {
            get {
                return ResourceManager.GetString("Order.Order.Group.Orderinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelregel.
        /// </summary>
        public static string Order_Order_Group_Orderline {
            get {
                return ResourceManager.GetString("Order.Order.Group.Orderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelregels.
        /// </summary>
        public static string Order_Order_Group_Orderlist {
            get {
                return ResourceManager.GetString("Order.Order.Group.Orderlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie.
        /// </summary>
        public static string Order_Orderline_Field_Category {
            get {
                return ResourceManager.GetString("Order.Orderline.Field.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afgeleverd.
        /// </summary>
        public static string Order_Orderline_Field_Closed {
            get {
                return ResourceManager.GetString("Order.Orderline.Field.Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverdatum.
        /// </summary>
        public static string Order_Orderline_Field_ClosedDate {
            get {
                return ResourceManager.GetString("Order.Orderline.Field.ClosedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal.
        /// </summary>
        public static string Order_Orderline_Field_Number {
            get {
                return ResourceManager.GetString("Order.Orderline.Field.Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stukprijs.
        /// </summary>
        public static string Order_Orderline_Field_Price {
            get {
                return ResourceManager.GetString("Order.Orderline.Field.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stukprijs in de valuta van de leverancier.
        /// </summary>
        public static string Order_Orderline_Field_Price_Tooltip {
            get {
                return ResourceManager.GetString("Order.Orderline.Field.Price.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string Order_Orderline_Field_Product {
            get {
                return ResourceManager.GetString("Order.Orderline.Field.Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Order_Orderline_Field_Project {
            get {
                return ResourceManager.GetString("Order.Orderline.Field.Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal.
        /// </summary>
        public static string Order_Orderline_Field_Total {
            get {
                return ResourceManager.GetString("Order.Orderline.Field.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalen.
        /// </summary>
        public static string Order_OrderlineTotals {
            get {
                return ResourceManager.GetString("Order.OrderlineTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal.
        /// </summary>
        public static string Order_OrderlineTotals_GrandTotal {
            get {
                return ResourceManager.GetString("Order.OrderlineTotals.GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order kosten.
        /// </summary>
        public static string Order_OrderlineTotals_Ordercosts {
            get {
                return ResourceManager.GetString("Order.OrderlineTotals.Ordercosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal bestelregels.
        /// </summary>
        public static string Order_OrderlineTotals_RowTotal {
            get {
                return ResourceManager.GetString("Order.OrderlineTotals.RowTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzendkosten.
        /// </summary>
        public static string Order_OrderlineTotals_ShippingCosts {
            get {
                return ResourceManager.GetString("Order.OrderlineTotals.ShippingCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stukprijs.
        /// </summary>
        public static string Order_Orderlist_Field_Price {
            get {
                return ResourceManager.GetString("Order.Orderlist.Field.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string Order_Orderlist_Field_Product {
            get {
                return ResourceManager.GetString("Order.Orderlist.Field.Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder geselkteerde bestelregel.
        /// </summary>
        public static string Order_Orderlist_Toolbar_Button_Delete {
            get {
                return ResourceManager.GetString("Order.Orderlist.Toolbar.Button.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe bestelregel toevoegen.
        /// </summary>
        public static string Order_Orderlist_Toolbar_Button_New {
            get {
                return ResourceManager.GetString("Order.Orderlist.Toolbar.Button.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzigingen opslaan.
        /// </summary>
        public static string Order_Orderlist_Toolbar_Button_Save {
            get {
                return ResourceManager.GetString("Order.Orderlist.Toolbar.Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voer de bestelling in per leverancier, per regel kan worden aangegeven of een artikel wordt meegenomen in de project kosten.
        /// </summary>
        public static string Order_Page_SubTitle {
            get {
                return ResourceManager.GetString("Order.Page.SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelling.
        /// </summary>
        public static string Order_Page_Title {
            get {
                return ResourceManager.GetString("Order.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelling.
        /// </summary>
        public static string Order_TabItemHeader_General {
            get {
                return ResourceManager.GetString("Order.TabItemHeader.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvullende informatie.
        /// </summary>
        public static string Order_TabItemHeader_Memo {
            get {
                return ResourceManager.GetString("Order.TabItemHeader.Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder geselecteerde bestelling.
        /// </summary>
        public static string Order_Toolbar_Button_Delete {
            get {
                return ResourceManager.GetString("Order.Toolbar.Button.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelling toevoegen.
        /// </summary>
        public static string Order_Toolbar_Button_New {
            get {
                return ResourceManager.GetString("Order.Toolbar.Button.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzigingen opslaan.
        /// </summary>
        public static string Order_Toolbar_Button_Save {
            get {
                return ResourceManager.GetString("Order.Toolbar.Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geselecteerde regel verwijderen.
        /// </summary>
        public static string toolbarButton_Action_Delete {
            get {
                return ResourceManager.GetString("toolbarButton.Action.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regel toevoegen.
        /// </summary>
        public static string toolbarButton_Action_New {
            get {
                return ResourceManager.GetString("toolbarButton.Action.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewijzigde gegevens opslaan.
        /// </summary>
        public static string toolbarButton_Action_Save {
            get {
                return ResourceManager.GetString("toolbarButton.Action.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vet.
        /// </summary>
        public static string toolbarButton_Font_Bold {
            get {
                return ResourceManager.GetString("toolbarButton.Font.Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursief.
        /// </summary>
        public static string toolbarButton_Font_Italic {
            get {
                return ResourceManager.GetString("toolbarButton.Font.Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onderstrepen.
        /// </summary>
        public static string toolbarButton_Font_Underline {
            get {
                return ResourceManager.GetString("toolbarButton.Font.Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terugspringen.
        /// </summary>
        public static string toolbarButton_Indent_Decrease {
            get {
                return ResourceManager.GetString("toolbarButton.Indent.Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspringen.
        /// </summary>
        public static string toolbarButton_Indent_Increase {
            get {
                return ResourceManager.GetString("toolbarButton.Indent.Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijst.
        /// </summary>
        public static string toolbarButton_List_Bullet {
            get {
                return ResourceManager.GetString("toolbarButton.List.Bullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genummerde lijst.
        /// </summary>
        public static string toolbarButton_List_Number {
            get {
                return ResourceManager.GetString("toolbarButton.List.Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieer.
        /// </summary>
        public static string toolbarButton_Text_Copy {
            get {
                return ResourceManager.GetString("toolbarButton.Text.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knippen.
        /// </summary>
        public static string toolbarButton_Text_Cut {
            get {
                return ResourceManager.GetString("toolbarButton.Text.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plak.
        /// </summary>
        public static string toolbarButton_Text_Paste {
            get {
                return ResourceManager.GetString("toolbarButton.Text.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opnieuw.
        /// </summary>
        public static string toolbarButton_Text_Redo {
            get {
                return ResourceManager.GetString("toolbarButton.Text.Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongedaan maken.
        /// </summary>
        public static string toolbarButton_Text_Undo {
            get {
                return ResourceManager.GetString("toolbarButton.Text.Undo", resourceCulture);
            }
        }
    }
}
