//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelbuilder.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cultures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cultures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modelbuilder.Languages.Cultures", typeof(Cultures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoriën.
        /// </summary>
        public static string metadataCategory_Page_Title {
            get {
                return ResourceManager.GetString("metadataCategory.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landen.
        /// </summary>
        public static string metadataCountry_Page_Title {
            get {
                return ResourceManager.GetString("metadataCountry.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta.
        /// </summary>
        public static string metadataCurrency_Page_Title {
            get {
                return ResourceManager.GetString("metadataCurrency.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producten.
        /// </summary>
        public static string metadataProduct_Page_Title {
            get {
                return ResourceManager.GetString("metadataProduct.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projecten.
        /// </summary>
        public static string metadataProject_Page_Title {
            get {
                return ResourceManager.GetString("metadataProject.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectgegevens.
        /// </summary>
        public static string metadataProject_TabItemHeader_General {
            get {
                return ResourceManager.GetString("metadataProject.TabItemHeader.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvullende informatie.
        /// </summary>
        public static string metadataProject_TabItemHeader_Memo {
            get {
                return ResourceManager.GetString("metadataProject.TabItemHeader.Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosten.
        /// </summary>
        public static string metadataProject_TabItemHeader_ProjectCosts {
            get {
                return ResourceManager.GetString("metadataProject.TabItemHeader.ProjectCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouwtijden.
        /// </summary>
        public static string metadataProject_TabItemHeader_TimeManagement {
            get {
                return ResourceManager.GetString("metadataProject.TabItemHeader.TimeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaglocaties.
        /// </summary>
        public static string metadataStorage_Page_Title {
            get {
                return ResourceManager.GetString("metadataStorage.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveranciers.
        /// </summary>
        public static string metadataSupplier_Page_Title {
            get {
                return ResourceManager.GetString("metadataSupplier.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werksoorten.
        /// </summary>
        public static string metadataWorktype_Page_Title {
            get {
                return ResourceManager.GetString("metadataWorktype.Page.Title", resourceCulture);
            }
        }
    }
}
